params: &S3PARAMS
  bucket: jacopen-concourse-bucket
  access_key_id: {{access_key_id}}
  secret_access_key: {{secret_access_key}}
  endpoint: s3.us-west-1.amazonaws.com
  region_name: us-west-1

resources:
- name: git-dockerbuild-sample
  type: git
  source:
    uri: https://github.com/jacopen/concourse-dockerbuild-sample.git
- name: binary
  type: s3
  source:
    <<: *S3PARAMS
    regexp: release/hoge-(.*).txt
- name: image
  type: docker-image
  source:
    repository: registry.udcp.info/private/test-image 
    username: {{registry_username}}
    password: {{registry_password}}

jobs:
  - name: build-dockerimage
    plan:
    - get: binary
    - get: git-dockerbuild-sample
    - task: copy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
        inputs:
          - name: git-dockerbuild-sample
          - name: binary
        outputs:
          - name: results
        run:
          path: sh
          args:
          - -c
          - |
            find .
            cat binary/version
            cp binary/hoge-`cat binary/version`.txt results/hoge.txt
            cp git-dockerbuild-sample/Dockerfile results/
    - task: show
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
        inputs:
          - name: results
        run:
          path: sh
          args:
          - -c
          - |
            find .
    - put: image
      params: {build: results}
