params: &S3PARAMS
  bucket: jacopen-concourse-bucket
  access_key_id: {{access_key_id}}
  secret_access_key: {{secret_access_key}}
  endpoint: s3.us-west-1.amazonaws.com
  region_name: us-west-1

resources:
- name: git-dockerbuild-sample
  type: git
  source:
    uri: https://github.com/jacopen/concourse-dockerbuild-sample.git
- name: binary
  type: s3
  source:
    <<: *S3PARAMS
    regexp: release/hoge-(.*).txt

jobs:
  - name: build-dockerimage
    plan:
    - get: binary
    - get: git-dockerbuild-sample
    - task: copy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: alpine
        inputs:
          - name: build-dockerimage
          - name: binary
        run:
          path: sh
          args:
          - -c
          - find .
